services:
  api-server:
    image: ghcr.io/ian-i-an/chat-server:latest
    container_name: spring-container
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    image: ghcr.io/ian-i-an/chat-nginx:latest
    container_name: nginx-container
    restart: unless-stopped
    volumes:
      - /home/ubuntu/frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - api-server