spring:
  application:
    name: chat-server
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET:thisiscreatekeyformypesonalprogject1234fortiwtterxxxx333}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}